name: Check Coveralls

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.x'

      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      
      - name: Install dependencies
        run: go get .

      - name: Build Check
        run: go build .

      - name: Test with the Go CLI
        run: go test -v -covermode=count -coverprofile=coverage.out
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2