name: Run test cases

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.15', '1.16', '1.17', '1.18.x', '1.19.x', '1.20.x', '1.21.x', '1.22.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      
      - name: Install dependencies
        run: go get .

      - name: Build Check
        run: go build .

      - name: Runing testcases 10 times
        run: go test -count=10 -v ./...
